# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94182f545049b55148729eeb5dc9ba09c5433647cb22c15e8acba405c160855e823f73859372f6d6fa04ff0dcf58f7c165c8ed854f96ce70e3936f853ea45c98

test:
  secret_key_base: 68dc7cde9c74f9c17c05a19410c86f3b37c41ae2166a7c2407d26e8945906c722a64a64884bc0f60165dbc8af27c923d4b19dc3c3da67c1c5c879796a379dba9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
